version: '3'

services:
    necro:
        build: ./necro
        ports:
            - "3080:3080"
            - "3081:3081"
        restart: always
        depends_on:
            - mongo
        volumes:
            - ./vol:/app
    mongo:
        image: mongo