version: '3'

services:
    necro:
        build: ./necro
        ports:
            - "4080:4080"
            - "4081:4081"
        restart: always
        depends_on:
            - mongo
        volumes:
            - ./vol:/app/vol
    mongo:
        image: mongo